# Generated by Django 2.1.4 on 2018-12-21 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20181221_2057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Brand',
            new_name='brand',
        ),
    ]
